return {
  -- === Ранние предметы (AE2, Draconic, базовые и т.д.) ===
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:35", displayName = "1024k МЭ жидкостный компонент хранилища", price = 261.91, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:34", displayName = "1024k МЭ компонент хранилища", price = 282.59, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:23", displayName = "16-битный чип", price = 2.255, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:37", displayName = "16K МЭ компонент хранения", price = 10.86, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:38", displayName = "16K МЭ ячейка хранения", price = 11.64, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:57", displayName = "16K хранилище создания", price = 12.168, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:56", displayName = "16Kb МЭ жидкостный компонент хранилища", price = 9.405, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:32", displayName = "1K МЭ компонент хранения", price = 0.825, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:33", displayName = "1K МЭ ячейка хранения", price = 1.61, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:53", displayName = "1K хранилище создания", price = 2.208, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:54", displayName = "1Kb МЭ жидкостный компонент хранилища", price = 0.825, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:55", displayName = "256Kb МЭ жидкостный компонент хранилища", price = 87.01, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:36", displayName = "256Kb МЭ компонент хранилища", price = 93.83, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:24", displayName = "32-битный чип", price = 4.51, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:36", displayName = "4K МЭ компонент хранения", price = 3.24, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:39", displayName = "4K МЭ ячейка хранения", price = 4.02, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:54", displayName = "4K хранилище создания", price = 4.548, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:55", displayName = "4Kb МЭ жидкостный компонент хранилища", price = 2.97, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:25", displayName = "64-битный чип", price = 14.223, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:38", displayName = "64K МЭ компонент хранения", price = 32.315, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:39", displayName = "64K МЭ ячейка хранения", price = 34.5, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:58", displayName = "64K хранилище создания", price = 36.487, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:57", displayName = "64Kb МЭ жидкостный компонент хранилища", price = 28.71, currency = "res" },

  { internalName = "gendustry:powerModule", displayName = "Отрубатель и сращиватель", price = 4.73, currency = "res" },
  { internalName = "gendustry:acclimatizer", displayName = "Акклиматизатор", price = 4.728, currency = "res" },
  { internalName = "Forestry:beealyzer", displayName = "Анализатор", price = 3.804, currency = "res" },
  { internalName = "gendustry:analyzer", displayName = "Анализатор агрокультур", price = 0.704, currency = "res" },
  { internalName = "thaumcraft:ItemResource:11", displayName = "Иссушающий нарост", price = 0.11, currency = "res" },
  { internalName = "thaumcraft:ItemResource", displayName = "Аквамарин", price = 18.678, currency = "res" },
  { internalName = "IC2:itemArmorBronzeChestplate", displayName = "Аккумуляторный ранец", price = 2.478, currency = "res" },
  { internalName = "IC2:itemPartIndustrialDiamond", displayName = "Алмазная электронная лампа", price = 0.578, currency = "res" },
  { internalName = "IC2:itemToolDrill", displayName = "Алмазный бур", price = 8.585, currency = "res" },
  { internalName = "IC2:itemPlateAlloy", displayName = "Армированная железная пластина", price = 8.8, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:13", displayName = "Базовая карта", price = 0.385, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:52", displayName = "Базовый чертёж", price = 2.31, currency = "res" },
  { internalName = "gendustry:geneSample", displayName = "Баллон сырой ДНК", price = 2.75, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiPart:480", displayName = "Бесконечная карта усиления", price = 1489.375, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemWirelessFluidTerminal", displayName = "Беспроводной МЭ жидкостный терминал", price = 21.362, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemWirelessTerminal", displayName = "Беспроводной МЭ универсальный терминал", price = 22.517, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:41", displayName = "Беспроводной приёмник", price = 3.322, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemWirelessTerminal", displayName = "Беспроводной терминал", price = 21.252, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemWirelessCraftingTerminal", displayName = "Беспроводной терминал создания", price = 483.924, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:31", displayName = "Биометрическая карта", price = 0.99, currency = "res" },
  { internalName = "IC2:blockMetal:3", displayName = "Блок закалённого железа", price = 1.98, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockCraftingUnit", displayName = "Блок обработки создания", price = 1.771, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockCraftingUnit", displayName = "Блок создания", price = 1.254, currency = "res" },
  { internalName = "Forestry:fertilizerBio", displayName = "Богатое удобрение", price = 0.011, currency = "res" },
  { internalName = "DraconicEvolution:wyvernBoots", displayName = "Ботинки Виверны", price = 485.162, currency = "res" },
  { internalName = "IC2:itemPlateBronze", displayName = "Бронзовая пластина", price = 0.11, currency = "res" },
  { internalName = "IC2:itemIngot:2", displayName = "Бронзовый слиток", price = 0.115, currency = "res" },
  { internalName = "minecraft:cobblestone", displayName = "Булыжник", price = 0.001, currency = "res" },
  { internalName = "ThermalFoundation:material:102", displayName = "Бурановый порошок", price = 0.22, currency = "res" },
  { internalName = "ThermalFoundation:material:103", displayName = "Бурановый стержень", price = 0.44, currency = "res" },
  { internalName = "minecraft:bucket", displayName = "Ведро", price = 0.33, currency = "res" },
  { internalName = "ThermalFoundation:bucket", displayName = "Ведро ледяного криотеума", price = 1.15, currency = "res" },
  { internalName = "ThermalFoundation:bucket", displayName = "Ведро резонирующего эндериума", price = 2.2, currency = "res" },
  { internalName = "minecraft:crafting_table", displayName = "Верстак", price = 0.055, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockCellWorkbench", displayName = "Верстак для ячеек", price = 0.715, currency = "res" },
  { internalName = "EnderIO:blockCapBank", displayName = "Вибрирующий блок конденсаторов", price = 21.068, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:12", displayName = "Вибрирующий кристалл", price = 1.76, currency = "res" },
  { internalName = "ThermalFoundation:material:72", displayName = "Вибрирующий сплав", price = 0.862, currency = "res" },
  { internalName = "minecraft:hopper", displayName = "Воронка", price = 0.55, currency = "res" },
  { internalName = "IC2:itemToolCutter", displayName = "Высекатель", price = 1.078, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:22", displayName = "Вычислительный процессор", price = 0.173, currency = "res" },
  { internalName = "IC2:itemToolWrench", displayName = "Гаечный ключ", price = 0.66, currency = "res" },
  { internalName = "IC2:blockGenerator", displayName = "Генератор", price = 1.078, currency = "res" },
  { internalName = "Forestry:engine", displayName = "Генератор биотоплива", price = 2.64, currency = "res" },
  { internalName = "IC2:blockGenerator:1", displayName = "Геотермальный генератор", price = 1.254, currency = "res" },
  { internalName = "minecraft:skull:5", displayName = "Голова стража Края", price = 2.2, currency = "res" },
  { internalName = "minecraft:gravel", displayName = "Гравий", price = 0.011, currency = "res" },
  { internalName = "minecraft:dirt", displayName = "Земля", price = 0.006, currency = "res" },
  { internalName = "DraconicEvolution:draconiumBlock", displayName = "Дракониевый блок", price = 28.728, currency = "res" },
  { internalName = "DraconicEvolution:draconiumIngot", displayName = "Дракониевый слиток", price = 3.192, currency = "res" },
  { internalName = "DraconicEvolution:draconicSword", displayName = "Драконий меч", price = 5285.345, currency = "res" },
  { internalName = "DraconicEvolution:draconicPickaxe", displayName = "Драконья кирка", price = 5735.199, currency = "res" },
  { internalName = "DraconicEvolution:draconicAxe", displayName = "Драконий топор", price = 5537.434, currency = "res" },
  { internalName = "DraconicEvolution:draconicShovel", displayName = "Драконья лопата", price = 5339.668, currency = "res" },
  { internalName = "DraconicEvolution:draconicBow", displayName = "Драконий лук", price = 5670.428, currency = "res" },
  { internalName = "DraconicEvolution:draconicHelm", displayName = "Драконий шлем", price = 5322.226, currency = "res" },
  { internalName = "DraconicEvolution:draconicChest", displayName = "Драконий нагрудник", price = 7268.832, currency = "res" },
  { internalName = "DraconicEvolution:wyvernLegs", displayName = "Драконьи поножи", price = 5359.678, currency = "res" },
  { internalName = "DraconicEvolution:wyvernBoots", displayName = "Драконьи ботинки", price = 5309.159, currency = "res" },
  { internalName = "DraconicEvolution:draconicStaffOfPower", displayName = "Драконий посох силы", price = 59923.0, currency = "res" },
  { internalName = "DraconicEvolution:draconicCore", displayName = "Драконье ядро", price = 20.0, currency = "res" },
  { internalName = "minecraft:emerald", displayName = "Гранат", price = 4.983, currency = "res" },
  { internalName = "minecraft:red_mushroom", displayName = "Гриб", price = 0.138, currency = "res" },
  { internalName = "minecraft:gold_ingot", displayName = "Золотой слиток", price = 0.15, currency = "res" },
  { internalName = "minecraft:dye:2", displayName = "Зелёный краситель", price = 0.11, currency = "res" },

  -- === Предметы из первого списка (базовые) ===
  { internalName = "DraconicEvolution:draconiumDust", displayName = "Дракониумовая пыль", price = 0.10, currency = "res" },
  { internalName = "dwcity:Splitter_dust", displayName = "Пыль Сплиттера", price = 0.10, currency = "res" },
  { internalName = "etfuturum:magma", displayName = "Магма-блок", price = 0.10, currency = "res" },
  { internalName = "ExtraTrees:food", displayName = "Кокос", price = 0.10, currency = "res" },
  { internalName = "Forestry:propolis", displayName = "Прополис", price = 0.10, currency = "res" },
  { internalName = "Genetics:misc", displayName = "Фермент", price = 0.10, currency = "res" },
  { internalName = "IC2:blockMetal", displayName = "Свинцовый блок", price = 0.90, currency = "res" },
  { internalName = "IC2:itemDust", displayName = "Оловянная пыль", price = 0.10, currency = "res" },
  { internalName = "IC2:itemIngot", displayName = "Оловянный слиток", price = 0.10, currency = "res" },
  { internalName = "IC2:itemUran238", displayName = "Уран-238", price = 0.10, currency = "res" },
  { internalName = "MineFactoryReloaded:plastic.raw", displayName = "Сырой пластик", price = 0.10, currency = "res" },
  { internalName = "MineFactoryReloaded:rubberwood.log", displayName = "Резиновая древесина", price = 0.10, currency = "res" },
  { internalName = "MineFactoryReloaded:rubberwood.sapling", displayName = "Саженец резинового дерева", price = 0.10, currency = "res" },
  { internalName = "ThermalFoundation:material", displayName = "Сера", price = 0.10, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockSkyStone", displayName = "Небесный камень", price = 0.90, currency = "res" },
  { internalName = "minecraft:apple", displayName = "Яблоко", price = 0.05, currency = "res" },
  { internalName = "minecraft:beef", displayName = "Сырое мясо", price = 0.10, currency = "res" },
  { internalName = "minecraft:dirt", displayName = "Земля", price = 0.01, currency = "res" },
  { internalName = "minecraft:double_plant", displayName = "Подсолнух", price = 0.10, currency = "res" },
  { internalName = "minecraft:iron_block", displayName = "Железный блок", price = 0.10, currency = "res" },
  { internalName = "minecraft:iron_ingot", displayName = "Железный слиток", price = 0.10, currency = "res" },
  { internalName = "minecraft:log", displayName = "Дубовое бревно", price = 0.15, currency = "res" },
  { internalName = "minecraft:reeds", displayName = "Сахарный тростник", price = 0.10, currency = "res" },
  { internalName = "minecraft:slime_ball", displayName = "Слизь", price = 0.30, currency = "res" },
  { internalName = "minecraft:stone", displayName = "Камень", price = 0.02, currency = "res" },
  { internalName = "minecraft:sugar", displayName = "Сахар", price = 0.10, currency = "res" },
  { internalName = "minecraft:wool", displayName = "Шерсть", price = 0.10, currency = "res" },

  -- === Новые предметы из последних скриншотов (9-15.png) ===
  { internalName = "minecraft:coal:1", displayName = "Измельчённый уголь", price = 0.055, currency = "res" },
  { internalName = "ThermalFoundation:material", displayName = "Изменчивый блок", price = 1.54, currency = "res" },
  { internalName = "ThermalFoundation:material", displayName = "Изменчивый кристалл", price = 0.42, currency = "res" },
  { internalName = "IC2:itemCable:1", displayName = "Изолированный медный провод", price = 0.035, currency = "res" },
  { internalName = "IC2:itemPartIndustrialDiamond", displayName = "Изолятор", price = 5.524, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:22", displayName = "Импульсный высекатель", price = 685.664, currency = "res" },
  { internalName = "ThermalFoundation:material:72", displayName = "Инваровая шестерня", price = 0.55, currency = "res" },
  { internalName = "ThermalFoundation:material:73", displayName = "Инваровый слиток", price = 0.11, currency = "res" },
  { internalName = "IC2:itemSolarPanel:1", displayName = "Индустриальная солнечная панель II уровня", price = 18.624, currency = "res" },
  { internalName = "IC2:itemSolarPanel:2", displayName = "Индустриальная солнечная панель III уровня", price = 150.06, currency = "res" },
  { internalName = "IC2:itemSolarPanel:3", displayName = "Индустриальная солнечная панель IV уровня", price = 1252.587, currency = "res" },
  { internalName = "IC2:itemSolarPanel:4", displayName = "Индустриальная солнечная панель V уровня", price = 4986.387, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Инженерный пресс для высекателя", price = 8.8, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:22", displayName = "Инженерный процессор", price = 0.518, currency = "res" },
  { internalName = "Forestry:beealyzer", displayName = "Инкубатор", price = 3.947, currency = "res" },
  { internalName = "gendustry:industrialApiary", displayName = "Инкубатор личинок улья", price = 21.08, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:24", displayName = "Интегральный процессор", price = 8.36, currency = "res" },
  { internalName = "OpenComputers:item:internetCard", displayName = "Интернет карта", price = 5.28, currency = "res" },
  { internalName = "ExtraTrees:food:1", displayName = "Какао-бобы", price = 0.55, currency = "res" },
  { internalName = "minecraft:cactus", displayName = "Кактус", price = 0.011, currency = "res" },
  { internalName = "Thaumcraft:ItemResource:11", displayName = "Камень тьмы", price = 76.362, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockCrystalGrowthAccelerator", displayName = "Камера для выращивания кристаллов", price = 506.943, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockCrystalGrowthAccelerator", displayName = "Камера мгновенного роста кристаллов", price = 1070.643, currency = "res" },
  { internalName = "minecraft:water_bucket", displayName = "Капсула воды", price = 0.055, currency = "res" },
  { internalName = "ThermalFoundation:bucketCryotheum", displayName = "Капсула хладагента", price = 0.55, currency = "res" },
  { internalName = "OpenComputers:item:dataCard1", displayName = "Карта данных (1-ый уровень)", price = 2.64, currency = "res" },
  { internalName = "OpenComputers:item:dataCard2", displayName = "Карта данных (2-ой уровень)", price = 7.425, currency = "res" },
  { internalName = "OpenComputers:item:dataCard3", displayName = "Карта данных (3-ий уровень)", price = 13.75, currency = "res" },
  { internalName = "OpenComputers:item", displayName = "Карта инвертирования", price = 0.715, currency = "res" },
  { internalName = "minecraft:redstone", displayName = "Карта красного камня", price = 0.385, currency = "res" },
  { internalName = "OpenComputers:item", displayName = "Карта нечёткости", price = 0.715, currency = "res" },
  { internalName = "OpenComputers:item:memory", displayName = "Карта памяти", price = 0.69, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:52", displayName = "Карта создания", price = 0.385, currency = "res" },
  { internalName = "OpenComputers:item", displayName = "Карта ускорения", price = 0.955, currency = "res" },
  { internalName = "OpenComputers:item", displayName = "Карта ёмкости", price = 0.495, currency = "res" },
  { internalName = "minecraft:potato", displayName = "Картофель", price = 0.022, currency = "res" },
  { internalName = "IC2:itemRecipe:1", displayName = "Катушка", price = 0.374, currency = "res" },
  { internalName = "IC2:blockMachine:3", displayName = "Квантовая индукционная плавильня", price = 1111.28, currency = "res" },
  { internalName = "IC2:itemQuantumArmor:2", displayName = "Квантовая кираса", price = 214.214, currency = "res" },
  { internalName = "IC2:blockMachine:2", displayName = "Квантовая печь", price = 122.4, currency = "res" },
  { internalName = "IC2:blockMachine:4", displayName = "Квантовая термальная центрифуга", price = 137.25, currency = "res" },
  { internalName = "IC2:itemQuantumArmor:3", displayName = "Квантовые ботинки", price = 105.468, currency = "res" },
  { internalName = "IC2:itemQuantumArmor:1", displayName = "Квантовые поножи", price = 107.448, currency = "res" },
  { internalName = "IC2:blockMachine:5", displayName = "Квантовый дробитель", price = 123.0, currency = "res" },
  { internalName = "IC2:blockMachine:6", displayName = "Квантовый компрессор", price = 123.0, currency = "res" },
  { internalName = "IC2:blockMachine:7", displayName = "Квантовый металлоформовочный механизм", price = 123.0, currency = "res" },
  { internalName = "IC2:blockMachine:8", displayName = "Квантовый молекулярный сборщик", price = 19.941, currency = "res" },
  { internalName = "IC2:blockMachine:9", displayName = "Квантовый преобразователь удачи", price = 177.0, currency = "res" },
  { internalName = "IC2:blockMachine:10", displayName = "Квантовый производитель лавы", price = 129.0, currency = "res" },
  { internalName = "IC2:blockMachine:11", displayName = "Квантовый рудопромывочный механизм", price = 123.0, currency = "res" },
  { internalName = "IC2:itemQuantumArmor:0", displayName = "Квантовый шлем", price = 131.95, currency = "res" },
  { internalName = "IC2:blockMachine:12", displayName = "Квантовый экстрактор", price = 122.445, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockQuartzGlass", displayName = "Кварцевое стекло", price = 0.11, currency = "res" },
  { internalName = "IC2:blockKineticGenerator", displayName = "Кинетический генератор", price = 3.366, currency = "res" },
  { internalName = "DraconicEvolution:wyvernPickaxe", displayName = "Кирка Виверны", price = 489.937, currency = "res" },
  { internalName = "ThermalFoundation:material", displayName = "Кислота", price = 1.553, currency = "res" },
  { internalName = "minecraft:bookshelf", displayName = "Книжная полка", price = 0.66, currency = "res" },
  { internalName = "minecraft:leather", displayName = "Кожа", price = 0.5, currency = "res" },
  { internalName = "ThermalDynamics:duct", displayName = "Коллектор", price = 0.396, currency = "res" },
  { internalName = "IC2:blockMachine", displayName = "Комбайн", price = 3.335, currency = "res" },
  { internalName = "IC2:itemPartCarbonPlate", displayName = "Композит", price = 0.495, currency = "res" },
  { internalName = "IC2:itemIngot:8", displayName = "Композитный слиток", price = 0.495, currency = "res" },
  { internalName = "ThermalDynamics:duct", displayName = "Компонентный теплообменник", price = 1.817, currency = "res" },
  { internalName = "ThermalDynamics:duct", displayName = "Компонентный теплоотвод", price = 1.848, currency = "res" },
  { internalName = "IC2:blockMachine:1", displayName = "Компрессор", price = 1.298, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Конденсатор материи", price = 0.825, currency = "res" },
  { internalName = "Forestry:alveary", displayName = "Кондиционер улья", price = 20.52, currency = "res" },
  { internalName = "IC2:blockMachine", displayName = "Консервирующий механизм", price = 1.826, currency = "res" },
  { internalName = "OpenComputers:item", displayName = "Контур печатной платы", price = 7.634, currency = "res" },
  { internalName = "OpenComputers:item", displayName = "Контур платы", price = 0.345, currency = "res" },
  { internalName = "minecraft:dye:15", displayName = "Костная мука", price = 0.055, currency = "res" },
  { internalName = "ExtraTrees:food", displayName = "Кофейные зёрна", price = 0.21, currency = "res" },
  { internalName = "IC2:itemRecipe", displayName = "Красная отдающая катушка", price = 0.22, currency = "res" },
  { internalName = "IC2:itemRecipe", displayName = "Красная принимающая катушка", price = 0.22, currency = "res" },
  { internalName = "IC2:itemRecipe", displayName = "Красная проводящая катушка", price = 0.22, currency = "res" },
  { internalName = "ThermalDynamics:duct:4", displayName = "Красная энергетическая флаксовная труба", price = 0.161, currency = "res" },
  { internalName = "ThermalExpansion:Cell", displayName = "Красная энергетическая ячейка", price = 8.625, currency = "res" },
  { internalName = "minecraft:torch", displayName = "Красный факел", price = 0.055, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Кремниевый пресс для высекателя", price = 8.8, currency = "res" },
  { internalName = "minecraft:flint", displayName = "Кремень", price = 0.176, currency = "res" },
  { internalName = "ThermalDynamics:duct:5", displayName = "Криостабилизированная флаксовная труба", price = 1.375, currency = "res" },
  { internalName = "TConstruct:materials:1", displayName = "Кристалл розовой слизи", price = 33.0, currency = "res" },
  { internalName = "EnderIO:blockCapBank:1", displayName = "Кристаллический конденсатор", price = 11.88, currency = "res" },
  { internalName = "ThermalFoundation:material", displayName = "Кристаллический сплав", price = 1.265, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Кубическая печать", price = 84.0, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Лазерная печать", price = 45.0, currency = "res" },
  { internalName = "IC2:itemPlateLapis", displayName = "Лазуритовая пластина", price = 0.058, currency = "res" },
  { internalName = "IC2:itemPartIndustrialDiamond", displayName = "Лазуритовая электронная лампа", price = 0.097, currency = "res" },
  { internalName = "ThermalFoundation:material:74", displayName = "Ламиумовый слиток", price = 0.22, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Легендарный чертёж", price = 125.059, currency = "res" },
  { internalName = "ThermalFoundation:material:102", displayName = "Ледяной порошок", price = 0.11, currency = "res" },
  { internalName = "minecraft:sticky_piston", displayName = "Липкий поршень", price = 0.165, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Логический пресс для высекателя", price = 8.8, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:23", displayName = "Логический процессор", price = 0.165, currency = "res" },
  { internalName = "minecraft:melon", displayName = "Ломтик арбуза", price = 0.022, currency = "res" },
  { internalName = "DraconicEvolution:wyvernShovel", displayName = "Лопата Виверны", price = 559.005, currency = "res" },
  { internalName = "DraconicEvolution:wyvernBow", displayName = "Лук Виверны", price = 492.0, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "МФУ", price = 9.2, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "МЭЭ", price = 9.328, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "МЭЭХ", price = 40.894, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:35", displayName = "МЭ 1024kb жидкостное хранилище", price = 304.725, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:34", displayName = "МЭ 1024kb хранилище", price = 285.205, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:38", displayName = "МЭ 16Kb жидкостное хранилище", price = 17.71, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:33", displayName = "МЭ 1Kb жидкостное хранилище", price = 5.28, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:55", displayName = "МЭ 256Kb жидкостное хранилище", price = 130.625, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial:36", displayName = "МЭ 256Kb хранилище", price = 105.3, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "МЭ 4096kb хранилище", price = 851.565, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "МЭ 4Kb жидкостное хранилище", price = 8.305, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "МЭ 64Kb жидкостное хранилище", price = 45.925, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemWirelessTerminal", displayName = "МЭ беспроводная точка доступа", price = 3.619, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockInterface", displayName = "МЭ жидкостный интерфейс", price = 0.88, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemWirelessFluidTerminal", displayName = "МЭ жидкостный терминал", price = 1.155, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "МЭ зарядник кварца", price = 582.642, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockInterface", displayName = "МЭ интерфейс", price = 1.127, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "МЭ камера квантовой связи", price = 13.056, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "МЭ квантовое кольцо", price = 4.278, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockController", displayName = "МЭ контроллер", price = 2.475, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "МЭ корпус ячейки хранения", price = 0.715, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockInterface", displayName = "МЭ монитор хранения", price = 0.594, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "МЭ накопитель", price = 1.771, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiPart:180", displayName = "МЭ плотный кабель - Изменчивый", price = 0.804, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "МЭ поддерживатель уровня", price = 188.991, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockInterface", displayName = "МЭ порт ввода/вывода", price = 3.905, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiPart:16", displayName = "МЭ стеклянный кабель - Изменчивый", price = 0.15, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockChest", displayName = "МЭ сундук", price = 1.806, currency = "res" },
}
