return {
  -- === Ранние предметы (AE2, Draconic, базовые и т.д.) ===
  { internalName = "AFSU:AFSU:0", displayName = "AFSU", price = 1.0, currency = "res" },
{ internalName = "AFSU:ALC:0", displayName = "AFB", price = 1.0, currency = "res" },
{ internalName = "AdvancedSolarPanel:asp_crafting_items:0", displayName = "Саннариум", price = 1.0, currency = "res" },
{ internalName = "AdvancedSolarPanel:asp_crafting_items:11", displayName = "Урановый слиток", price = 1.0, currency = "res" },
{ internalName = "AdvancedSolarPanel:asp_crafting_items:12", displayName = "МТ-ядро", price = 1.0, currency = "res" },
{ internalName = "AdvancedSolarPanel:asp_crafting_items:2", displayName = "Облучённый уран", price = 1.0, currency = "res" },
{ internalName = "AdvancedSolarPanel:asp_crafting_items:3", displayName = "Обогащённый саннариум", price = 1.0, currency = "res" },
{ internalName = "AdvancedSolarPanel:asp_crafting_items:5", displayName = "Облучённая стеклянная панель", price = 1.0, currency = "res" },
{ internalName = "AdvancedSolarPanel:asp_crafting_items:7", displayName = "Усиленная иридиево-железная пластина", price = 1.0, currency = "res" },
{ internalName = "AdvancedSolarPanel:asp_crafting_items:8", displayName = "Облучённая усиленная пластина", price = 1.0, currency = "res" },
{ internalName = "AdvancedSolarPanel:asp_crafting_items:9", displayName = "Кусочек саннариума", price = 1.0, currency = "res" },
{ internalName = "Avaritia:Dire_Crafting:0", displayName = "Dire Crafting Table", price = 1.0, currency = "res" },
{ internalName = "BinnieCore:containerBucket:129", displayName = "Ведро со смолой", price = 1.0, currency = "res" },
{ internalName = "BinnieCore:containerBucket:131", displayName = "Ведро со скипидаром", price = 1.0, currency = "res" },
{ internalName = "BinnieCore:containerBucket:768", displayName = "Ростовая среда", price = 1.0, currency = "res" },
{ internalName = "BinnieCore:containerGlass:129", displayName = "Стекло со смолой", price = 1.0, currency = "res" },
{ internalName = "BinnieCore:containerGlass:131", displayName = "Стекло со скипидаром", price = 1.0, currency = "res" },
{ internalName = "BinnieCore:containerGlass:768", displayName = "Ростовая среда (стекло)", price = 1.0, currency = "res" },
{ internalName = "BinnieCore:storage:0", displayName = "Отсек", price = 1.0, currency = "res" },
{ internalName = "BinnieCore:storage:1", displayName = "Медный отсек", price = 1.0, currency = "res" },
{ internalName = "BinnieCore:storage:3", displayName = "Железный отсек", price = 1.0, currency = "res" },
{ internalName = "BinnieCore:storage:4", displayName = "Золотой отсек", price = 1.0, currency = "res" },
{ internalName = "BinnieCore:storage:5", displayName = "Алмазный отсек", price = 1.0, currency = "res" },
{ internalName = "Botany:database:0", displayName = "База данных ботаника", price = 1.0, currency = "res" },
{ internalName = "Botany:database:1", displayName = "База данных мастера-ботаника", price = 1.0, currency = "res" },
{ internalName = "Botany:misc:1", displayName = "Порошок целлюлозы", price = 1.0, currency = "res" },
{ internalName = "Botany:misc:2", displayName = "Порошок мульчи", price = 1.0, currency = "res" },
{ internalName = "Botany:misc:7", displayName = "Гербицид", price = 1.0, currency = "res" },
{ internalName = "Botany:soilMeter:0", displayName = "Измеритель почвы", price = 1.0, currency = "res" },
{ internalName = "Botany:trowelStone:0", displayName = "Каменный мастерок", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Core:diamondGearItem:0", displayName = "Алмазная шестерня", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Core:engineBlock:0", displayName = "Редстоуновый двигатель", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Core:engineBlock:1", displayName = "Двигатель Стирлинга", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Core:engineBlock:2", displayName = "Двигатель внутреннего сгорания", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Core:stoneGearItem:0", displayName = "Каменная шестерня", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Core:woodenGearItem:0", displayName = "Деревянная шестерня", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Energy:bucketOil:0", displayName = "Ведро нефти", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Factory:pumpBlock:0", displayName = "Насос", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Factory:refineryBlock:0", displayName = "Нефтеперегонный завод", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Factory:tankBlock:0", displayName = "Цистерна", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Silicon:laserBlock:0", displayName = "Лазер", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Silicon:laserTableBlock:0", displayName = "Сборочный стол", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Silicon:laserTableBlock:1", displayName = "Продвинутый верстак", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Silicon:laserTableBlock:2", displayName = "Стол интеграции", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Silicon:laserTableBlock:3", displayName = "Стол зарядки", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Silicon:laserTableBlock:4", displayName = "Стол программирования", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Silicon:redstoneChipset:0", displayName = "Редстоуновый чипсет", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Silicon:redstoneChipset:2", displayName = "Золотой чипсет", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Silicon:redstoneChipset:3", displayName = "Алмазный чипсет", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Silicon:redstoneChipset:4", displayName = "Пульсирующий чипсет", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Silicon:redstoneChipset:7", displayName = "Изумрудный чипсет", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Transport:item.buildcraftPipe.pipefluidsvoid:0", displayName = "Труба пустоты для жидкостей", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Transport:item.buildcraftPipe.pipeitemsvoid:0", displayName = "Транспортная труба пустоты", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Transport:item.buildcraftPipe.pipestructurecobblestone:0", displayName = "Структурная булыжниковая труба", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Transport:pipeFacade:0", displayName = "Фасад: ", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Transport:pipeGate:0", displayName = "Базовый гейт", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Transport:pipePowerAdapter:0", displayName = "Адаптер питания", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Transport:pipeWaterproof:0", displayName = "Герметик для труб", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Transport:pipeWire:0", displayName = "Красный провод для труб", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Transport:pipeWire:1", displayName = "Синий провод для труб", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Transport:pipeWire:2", displayName = "Зелёный провод для труб", price = 1.0, currency = "res" },
{ internalName = "BuildCraft|Transport:pipeWire:3", displayName = "Жёлтый провод для труб", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:awakenedCore:0", displayName = "Пробуждённое ядро", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:draconicAxe:0", displayName = "Драконий топор", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:draconicBlock:0", displayName = "Блок пробуждённого дракония", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:draconicBow:0", displayName = "Драконий лук", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:draconicCore:0", displayName = "Драконье ядро", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:draconicDistructionStaff:0", displayName = "Драконий посох силы", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:draconicIngot:0", displayName = "Пробуждённый дракониевый слиток", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:draconicPickaxe:0", displayName = "Драконья кирка", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:draconicShovel:0", displayName = "Драконья лопата", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:draconicSword:0", displayName = "Драконий меч", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:draconium:0", displayName = "Дракониевый блок", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:draconium:1", displayName = "Камень воскрешения", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:draconium:2", displayName = "Заряженный дракониевый блок", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:draconiumDust:0", displayName = "Дракониевая пыль", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:draconiumEnergyCore:0", displayName = "Энергетическое ядро виверны", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:draconiumEnergyCore:1", displayName = "Драконье энергетическое ядро", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:draconiumFluxCapacitor:0", displayName = "Потоковый конденсатор виверны", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:draconiumFluxCapacitor:1", displayName = "Драконий потоковый конденсатор", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:draconiumIngot:0", displayName = "Дракониевый слиток", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:energyCrystal:0", displayName = "Энергетическое реле", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:energyCrystal:1", displayName = "Продвинутое энергореле", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:energyCrystal:2", displayName = "Энергетический трансивер", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:energyCrystal:3", displayName = "Продвинутый энерготрансивер", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:energyCrystal:4", displayName = "Беспроводной энерготрансивер", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:energyInfuser:0", displayName = "Энергетический наполнитель", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:infusedObsidian:0", displayName = "Обсидиан, пропитанный драконием", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:upgradeModifier:0", displayName = "Модификатор улучшений", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:wyvernBow:0", displayName = "Лук виверны", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:wyvernCore:0", displayName = "Ядро виверны", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:wyvernPickaxe:0", displayName = "Кирка виверны", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:wyvernShovel:0", displayName = "Лопата виверны", price = 1.0, currency = "res" },
{ internalName = "DraconicEvolution:wyvernSword:0", displayName = "Меч виверны", price = 1.0, currency = "res" },
{ internalName = "DwQuests:StarAtlas:0", displayName = "Звёздный атлас", price = 1.0, currency = "res" },
{ internalName = "EnderIO:blockAlloySmelter:0", displayName = "Плавильня сплавов", price = 1.0, currency = "res" },
{ internalName = "EnderIO:blockDarkIronBars:0", displayName = "Прутья тёмной стали", price = 1.0, currency = "res" },
{ internalName = "EnderIO:blockElectricLight:0", displayName = "Электрический светильник", price = 1.0, currency = "res" },
{ internalName = "EnderIO:blockEnderIo:0", displayName = "Эндер ИО", price = 1.0, currency = "res" },
{ internalName = "EnderIO:blockEndermanSkull:0", displayName = "Голова эндермена", price = 1.0, currency = "res" },
{ internalName = "EnderIO:blockEndermanSkull:2", displayName = "Голова измученного эндермена", price = 1.0, currency = "res" },
{ internalName = "EnderIO:blockExperienceObelisk:0", displayName = "Обелиск опыта", price = 1.0, currency = "res" },
{ internalName = "EnderIO:blockFarmStation:0", displayName = "Фермерская станция", price = 1.0, currency = "res" },
{ internalName = "EnderIO:blockFusedQuartz:0", displayName = "Плавленый кварц", price = 1.0, currency = "res" },
{ internalName = "EnderIO:blockFusedQuartz:1", displayName = "Совершенно прозрачное стекло", price = 1.0, currency = "res" },
{ internalName = "EnderIO:blockKillerJoe:0", displayName = "Убийца Джо", price = 1.0, currency = "res" },
{ internalName = "EnderIO:blockPainter:0", displayName = "Покрасочная машина", price = 1.0, currency = "res" },
{ internalName = "EnderIO:blockReinforcedObsidian:0", displayName = "Усиленный обсидиан", price = 1.0, currency = "res" },
{ internalName = "EnderIO:blockReservoir:0", displayName = "Резервуар", price = 1.0, currency = "res" },
{ internalName = "EnderIO:blockSagMill:0", displayName = "Измельчитель SAG", price = 1.0, currency = "res" },
{ internalName = "EnderIO:blockSliceAndSplice:0", displayName = "Слайс-н-Сплайс", price = 1.0, currency = "res" },
{ internalName = "EnderIO:blockSoulBinder:0", displayName = "Привязчик душ", price = 1.0, currency = "res" },
{ internalName = "EnderIO:blockTank:0", displayName = "Цистерна для жидкостей", price = 1.0, currency = "res" },
{ internalName = "EnderIO:blockTransceiver:0", displayName = "Пространственный трансивер", price = 1.0, currency = "res" },
{ internalName = "EnderIO:blockVacuumChest:0", displayName = "Вакуумный сундук", price = 1.0, currency = "res" },
{ internalName = "EnderIO:blockVat:0", displayName = "Чан", price = 1.0, currency = "res" },
{ internalName = "EnderIO:blockWirelessCharger:0", displayName = "Беспроводное зарядное устройство", price = 1.0, currency = "res" },
{ internalName = "EnderIO:bucketCloud_seed:0", displayName = "Ведро с засевом облаков", price = 1.0, currency = "res" },
{ internalName = "EnderIO:bucketCloud_seed_concentrated:0", displayName = "Ведро с концентрированным засевом облаков", price = 1.0, currency = "res" },
{ internalName = "EnderIO:bucketFire_water:0", displayName = "Ведро огненной воды", price = 1.0, currency = "res" },
{ internalName = "EnderIO:bucketHootch:0", displayName = "Ведро с хучем", price = 1.0, currency = "res" },
{ internalName = "EnderIO:bucketLiquid_sunshine:0", displayName = "Ведро жидкого солнечного света", price = 1.0, currency = "res" },
{ internalName = "EnderIO:bucketNutrient_distillation:0", displayName = "Ведро дистиллята питательных веществ", price = 1.0, currency = "res" },
{ internalName = "EnderIO:bucketRocket_fuel:0", displayName = "Ведро ракетного топлива", price = 1.0, currency = "res" },
{ internalName = "EnderIO:item.darkSteel_boots:0", displayName = "Тёмные ботинки", price = 1.0, currency = "res" },
{ internalName = "EnderIO:item.darkSteel_leggings:0", displayName = "Тёмные поножи", price = 1.0, currency = "res" },
{ internalName = "EnderIO:item.darkSteel_sword:0", displayName = "Эндер", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemAlloy:0", displayName = "Электротехническая сталь", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemAlloy:1", displayName = "Энергетический сплав", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemAlloy:2", displayName = "Вибрирующий сплав", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemAlloy:3", displayName = "Редстоуновый сплав", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemAlloy:4", displayName = "Проводящее железо", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemAlloy:5", displayName = "Пульсирующее железо", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemAlloy:6", displayName = "Тёмная сталь", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemAlloy:7", displayName = "Соулариум", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemAlloy:8", displayName = "Эндер-сталь", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemAlloyEndergy:1", displayName = "Кристаллический сплав", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemAlloyEndergy:2", displayName = "Мелодичный сплав", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemAlloyEndergy:3", displayName = "Звёздный сплав", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemBasicCapacitor:0", displayName = "Базовый конденсатор", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemBasicCapacitor:1", displayName = "Двухслойный конденсатор", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemBasicCapacitor:2", displayName = "Октадный конденсатор", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemBasicCapacitor:3", displayName = "Кристаллический конденсатор", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemBasicCapacitor:4", displayName = "Мелодичный конденсатор", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemBasicCapacitor:5", displayName = "Звёздный конденсатор", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemBasicCapacitor:6", displayName = "Тотемный конденсатор", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemBasicFilterUpgrade:0", displayName = "Базовый фильтр предметов", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemBasicFilterUpgrade:1", displayName = "Продвинутый фильтр предметов", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemBrokenSpawner:0", displayName = "Сломанный спаунер", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemConduitFacade:0", displayName = "Облицовка труб", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemConduitFacade:1", displayName = "Упрочнённая облицовка труб", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemConduitProbe:0", displayName = "Зонд для труб", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemExtractSpeedUpgrade:0", displayName = "Улучшение скорости предметных труб", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemFrankenSkull:1", displayName = "Z-логический контроллер", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemFrankenSkull:3", displayName = "Эндер-резонатор", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemFunctionUpgrade:0", displayName = "Улучшение удалённого восприятия", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemGrindingBall:6", displayName = "Шар из тёмной стали", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemItemConduit:0", displayName = "Предметная труба", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemLiquidConduit:3", displayName = "Кристаллическая эндер-жидкостная труба", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemLiquidConduit:4", displayName = "Кристаллическая розово-слизевая эндер-жидкостная труба", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemLiquidConduit:5", displayName = "Мелодичная эндер-жидкостная труба", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemLiquidConduit:6", displayName = "Звёздная эндер-жидкостная труба", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemMEConduit:0", displayName = "МЭ-труба", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemMEConduit:1", displayName = "Плотная МЭ-труба", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemMachinePart:0", displayName = "Корпус машины", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemMachinePart:1", displayName = "Базовая шестерня", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemMaterial:0", displayName = "Кремний", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemMaterial:1", displayName = "Связующее для труб", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemMaterial:14", displayName = "Крупицы пьезоэлектричества", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemMaterial:15", displayName = "Крупицы вибрации", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemMaterial:2", displayName = "Композитное связующее", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemMaterial:3", displayName = "Кусочек пульсирующего железа", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemMaterial:4", displayName = "Кусочек вибрирующего сплава", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemMaterial:5", displayName = "Пульсирующий кристалл", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemMaterial:6", displayName = "Вибрирующий кристалл", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemOCConduit:0", displayName = "Сетевой кабель (OC)", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemPowderIngot:5", displayName = "Порошок жемчуга Эндера", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemPowderIngot:6", displayName = "Основа эндериума", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemPowerConduit:0", displayName = "Энергетическая труба", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemPowerConduit:2", displayName = "Эндер-энергетическая труба", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemPowerConduitEndergy:10", displayName = "Мелодичная энерготруба", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemRedstoneConduit:2", displayName = "Изолированная редстоун-труба", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemSoulVessel:0", displayName = "Фиал души", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemTravelStaff:16", displayName = "Посох перемещения", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemXpTransfer:0", displayName = "Жезл опыта", price = 1.0, currency = "res" },
{ internalName = "EnderIO:itemYetaWrench:0", displayName = "Ета-ключ", price = 1.0, currency = "res" },
{ internalName = "ExtraBees:alveary:0", displayName = "Мутатор", price = 1.0, currency = "res" },
{ internalName = "ExtraBees:alveary:1", displayName = "Корпус рамок", price = 1.0, currency = "res" },
{ internalName = "ExtraBees:alveary:2", displayName = "Дождевой щиток", price = 1.0, currency = "res" },
{ internalName = "ExtraBees:alveary:3", displayName = "Освещение альвеария", price = 1.0, currency = "res" },
{ internalName = "ExtraBees:alveary:4", displayName = "Электрический стимулятор", price = 1.0, currency = "res" },
{ internalName = "ExtraBees:alveary:5", displayName = "Инкубатор", price = 1.0, currency = "res" },
{ internalName = "ExtraBees:alveary:6", displayName = "Трансмиссия альвеария", price = 1.0, currency = "res" },
{ internalName = "ExtraBees:hive:1", displayName = "Каменный улей", price = 1.0, currency = "res" },
{ internalName = "ExtraBees:hiveFrame.soul:0", displayName = "Рамка души", price = 1.0, currency = "res" },
{ internalName = "ExtraBees:misc:1", displayName = "Осколок алмаза", price = 1.0, currency = "res" },
{ internalName = "ExtraBees:misc:6", displayName = "Железные крупицы", price = 1.0, currency = "res" },
{ internalName = "ExtraBees:propolis:0", displayName = "Водянистый прополис", price = 1.0, currency = "res" },
{ internalName = "ExtraTrees:food:50", displayName = "Кокос", price = 1.0, currency = "res" },
{ internalName = "ExtraUtilities:colorStoneBrick:10", displayName = "Окрашенные каменные кирпичи (Фиолетовая частота)", price = 1.0, currency = "res" },
{ internalName = "ExtraUtilities:colorStoneBrick:11", displayName = "Окрашенные каменные кирпичи (Синяя частота)", price = 1.0, currency = "res" },
{ internalName = "ExtraUtilities:colorStoneBrick:4", displayName = "Окрашенные каменные кирпичи (Жёлтая частота)", price = 1.0, currency = "res" },
{ internalName = "ExtraUtilities:colorStoneBrick:5", displayName = "Окрашенные каменные кирпичи (Лаймовая частота)", price = 1.0, currency = "res" },
{ internalName = "ExtraUtilities:colorWoodPlanks:1", displayName = "Окрашенные дубовые доски (Оранжевая частота)", price = 1.0, currency = "res" },
{ internalName = "ExtraUtilities:colorWoodPlanks:6", displayName = "Окрашенные дубовые доски (Розовая частота)", price = 1.0, currency = "res" },
{ internalName = "ExtraUtilities:decorativeBlock1:1", displayName = "Эндер-пропитанный обсидиан", price = 1.0, currency = "res" },
{ internalName = "ExtraUtilities:decorativeBlock1:9", displayName = "Песчаное стекло", price = 1.0, currency = "res" },
{ internalName = "ExtraUtilities:decorativeBlock2:0", displayName = "Утолщённое стекло", price = 1.0, currency = "res" },
{ internalName = "ExtraUtilities:pipes:11", displayName = "Энергетическая труба", price = 1.0, currency = "res" },
{ internalName = "ExtraUtilities:plant/ender_lilly:0", displayName = "Семена эндер-лилии", price = 1.0, currency = "res" },
{ internalName = "Forestry:alveary:0", displayName = "Альвеарий", price = 1.0, currency = "res" },
{ internalName = "Forestry:alveary:2", displayName = "Роитель", price = 1.0, currency = "res" },
{ internalName = "Forestry:alveary:3", displayName = "Вентилятор альвеария", price = 1.0, currency = "res" },
{ internalName = "Forestry:alveary:4", displayName = "Обогреватель альвеария", price = 1.0, currency = "res" },
{ internalName = "Forestry:alveary:5", displayName = "Гигрорегулятор альвеария", price = 1.0, currency = "res" },
{ internalName = "Forestry:alveary:6", displayName = "Стабилизатор альвеария", price = 1.0, currency = "res" },
{ internalName = "Forestry:alveary:7", displayName = "Сито альвеария", price = 1.0, currency = "res" },
{ internalName = "Forestry:ambrosia:0", displayName = "Амброзия", price = 1.0, currency = "res" },
{ internalName = "Forestry:apatite:0", displayName = "Апатит", price = 1.0, currency = "res" },
{ internalName = "Forestry:apiculture:0", displayName = "Пасека", price = 1.0, currency = "res" },
{ internalName = "Forestry:apiculture:2", displayName = "Пчелиный домик", price = 1.0, currency = "res" },
{ internalName = "Forestry:apicultureChest:0", displayName = "Сундук пасечника", price = 1.0, currency = "res" },
{ internalName = "Forestry:arboriculture:0", displayName = "Сундук арбориста", price = 1.0, currency = "res" },
{ internalName = "Forestry:ash:0", displayName = "Пепел", price = 1.0, currency = "res" },
{ internalName = "Forestry:beeCombs:14", displayName = "Пшеничный сот", price = 1.0, currency = "res" },
{ internalName = "Forestry:beeswax:0", displayName = "Пчелиный воск", price = 1.0, currency = "res" },
{ internalName = "Forestry:beverage:0", displayName = "Недозрелый мёд", price = 1.0, currency = "res" },
{ internalName = "Forestry:beverage:2", displayName = "Мёд", price = 1.0, currency = "res" },
{ internalName = "Forestry:bucketBiomass:0", displayName = "Ведро биомассы", price = 1.0, currency = "res" },
{ internalName = "Forestry:bucketEthanol:0", displayName = "Ведро этанола", price = 1.0, currency = "res" },
{ internalName = "Forestry:bucketHoney:0", displayName = "Ведро мёда", price = 1.0, currency = "res" },
{ internalName = "Forestry:bucketIce:0", displayName = "Ведро дроблёного льда", price = 1.0, currency = "res" },
{ internalName = "Forestry:bucketJuice:0", displayName = "Ведро сока", price = 1.0, currency = "res" },
{ internalName = "Forestry:bucketMead:0", displayName = "Ведро медовухи", price = 1.0, currency = "res" },
{ internalName = "Forestry:bucketSeedOil:0", displayName = "Ведро растительного масла", price = 1.0, currency = "res" },
{ internalName = "Forestry:bucketShortMead:0", displayName = "Ведро недозрелого мёда", price = 1.0, currency = "res" },
{ internalName = "Forestry:butterflyGE:0", displayName = "Palaeno Sulphur", price = 1.0, currency = "res" },
{ internalName = "Forestry:chipsets:1", displayName = "Улучшенная монтажная плата", price = 1.0, currency = "res" },
{ internalName = "Forestry:chipsets:3", displayName = "Сложная монтажная плата", price = 1.0, currency = "res" },
{ internalName = "Forestry:core:0", displayName = "Анализатор", price = 1.0, currency = "res" },
{ internalName = "Forestry:craftingMaterial:2", displayName = "Шёлковая нить", price = 1.0, currency = "res" },
{ internalName = "Forestry:craftingMaterial:3", displayName = "Тканый шёлк", price = 1.0, currency = "res" },
{ internalName = "Forestry:craftingMaterial:5", displayName = "Осколок льда", price = 1.0, currency = "res" },
{ internalName = "Forestry:craftingMaterial:6", displayName = "Ароматизированная панель", price = 1.0, currency = "res" },
{ internalName = "Forestry:engine:0", displayName = "Электрический двигатель", price = 1.0, currency = "res" },
{ internalName = "Forestry:engine:3", displayName = "Биогенератор", price = 1.0, currency = "res" },
{ internalName = "Forestry:factory2:0", displayName = "Термионный фабрикатор", price = 1.0, currency = "res" },
{ internalName = "Forestry:factory:1", displayName = "Плотник", price = 1.0, currency = "res" },
{ internalName = "Forestry:factory:2", displayName = "Центрифуга", price = 1.0, currency = "res" },
{ internalName = "Forestry:factory:3", displayName = "Бродильня", price = 1.0, currency = "res" },
{ internalName = "Forestry:factory:5", displayName = "Соковыжималка", price = 1.0, currency = "res" },
{ internalName = "Forestry:factory:6", displayName = "Дистиллятор", price = 1.0, currency = "res" },
{ internalName = "Forestry:fertilizerCompound:0", displayName = "Удобрение", price = 1.0, currency = "res" },
{ internalName = "Forestry:frameImpregnated:0", displayName = "Пропитанная рамка", price = 1.0, currency = "res" },
{ internalName = "Forestry:frameUntreated:0", displayName = "Необработанная рамка", price = 1.0, currency = "res" },
{ internalName = "Forestry:grafter:0", displayName = "Прививочный нож", price = 1.0, currency = "res" },
{ internalName = "Forestry:honeyDrop:0", displayName = "Капля мёда", price = 1.0, currency = "res" },
{ internalName = "Forestry:honeydew:0", displayName = "Медвяная роса", price = 1.0, currency = "res" },
{ internalName = "Forestry:honeyedSlice:0", displayName = "Медовый ломтик", price = 1.0, currency = "res" },
{ internalName = "Forestry:impregnatedCasing:0", displayName = "Пропитанный корпус", price = 1.0, currency = "res" },
{ internalName = "Forestry:lepidopterology:0", displayName = "Сундук лепидоптеролога", price = 1.0, currency = "res" },
{ internalName = "Forestry:minerBag:0", displayName = "Рюкзак шахтёра", price = 1.0, currency = "res" },
{ internalName = "Forestry:mulch:0", displayName = "Мульча", price = 1.0, currency = "res" },
{ internalName = "Forestry:naturalistHelmet:0", displayName = "Очки", price = 1.0, currency = "res" },
{ internalName = "Forestry:oakStick:0", displayName = "Пропитанная палка", price = 1.0, currency = "res" },
{ internalName = "Forestry:phosphor:0", displayName = "Фосфор", price = 1.0, currency = "res" },
{ internalName = "Forestry:pollen:0", displayName = "Пыльцевой комок", price = 1.0, currency = "res" },
{ internalName = "Forestry:pollen:1", displayName = "Кристаллический пыльцевой комок", price = 1.0, currency = "res" },
{ internalName = "Forestry:pollenFertile:0", displayName = "Пыльца яблоневого дуба", price = 1.0, currency = "res" },
{ internalName = "Forestry:propolis:0", displayName = "Прополис", price = 1.0, currency = "res" },
{ internalName = "Forestry:propolis:2", displayName = "Пульсирующий прополис", price = 1.0, currency = "res" },
{ internalName = "Forestry:refractoryWax:0", displayName = "Огнеупорный воск", price = 1.0, currency = "res" },
{ internalName = "Forestry:royalJelly:0", displayName = "Маточное молочко", price = 1.0, currency = "res" },
{ internalName = "Forestry:sapling:0", displayName = "Саженец тропического дерева", price = 1.0, currency = "res" },
{ internalName = "Forestry:scoop:0", displayName = "Сачок", price = 1.0, currency = "res" },
{ internalName = "Forestry:solderingIron:0", displayName = "Паяльник", price = 1.0, currency = "res" },
{ internalName = "Forestry:sturdyMachine:0", displayName = "Прочный корпус", price = 1.0, currency = "res" },
{ internalName = "Forestry:thermionicTubes:0", displayName = "Медная электронная лампа", price = 1.0, currency = "res" },
{ internalName = "Forestry:thermionicTubes:1", displayName = "Оловянная электронная лампа", price = 1.0, currency = "res" },
{ internalName = "Forestry:thermionicTubes:10", displayName = "Апатиновая электронная лампа", price = 1.0, currency = "res" },
{ internalName = "Forestry:thermionicTubes:11", displayName = "Лазуритовая электронная лампа", price = 1.0, currency = "res" },
{ internalName = "Forestry:thermionicTubes:12", displayName = "Эндер-электронная лампа", price = 1.0, currency = "res" },
{ internalName = "Forestry:thermionicTubes:3", displayName = "Железная электронная лампа", price = 1.0, currency = "res" },
{ internalName = "Forestry:thermionicTubes:4", displayName = "Золотая электронная лампа", price = 1.0, currency = "res" },
{ internalName = "Forestry:thermionicTubes:5", displayName = "Алмазная электронная лампа", price = 1.0, currency = "res" },
{ internalName = "Forestry:thermionicTubes:6", displayName = "Обсидиановая электронная лампа", price = 1.0, currency = "res" },
{ internalName = "Forestry:thermionicTubes:7", displayName = "Пылающая электронная лампа", price = 1.0, currency = "res" },
{ internalName = "Forestry:thermionicTubes:8", displayName = "Обрезиненная электронная лампа", price = 1.0, currency = "res" },
{ internalName = "Forestry:thermionicTubes:9", displayName = "Изумрудная электронная лампа", price = 1.0, currency = "res" },
{ internalName = "Forestry:waxCapsule:0", displayName = "Восковая капсула", price = 1.0, currency = "res" },
{ internalName = "Forestry:woodPulp:0", displayName = "Древесная масса", price = 1.0, currency = "res" },
{ internalName = "Genetics:advMachine:0", displayName = "Сплайсер", price = 1.0, currency = "res" },
{ internalName = "Genetics:analyst:0", displayName = "Аналитик", price = 1.0, currency = "res" },
{ internalName = "Genetics:database:0", displayName = "База данных генов", price = 1.0, currency = "res" },
{ internalName = "Genetics:labMachine:0", displayName = "Лабораторный штатив", price = 1.0, currency = "res" },
{ internalName = "Genetics:labMachine:1", displayName = "Анализатор", price = 1.0, currency = "res" },
{ internalName = "Genetics:labMachine:2", displayName = "Инкубатор", price = 1.0, currency = "res" },
{ internalName = "Genetics:labMachine:3", displayName = "Генофонд", price = 1.0, currency = "res" },
{ internalName = "Genetics:labMachine:4", displayName = "Акклиматизатор", price = 1.0, currency = "res" },
{ internalName = "Genetics:machine:0", displayName = "Изолятор", price = 1.0, currency = "res" },
{ internalName = "Genetics:machine:1", displayName = "Секвенатор", price = 1.0, currency = "res" },
{ internalName = "Genetics:machine:2", displayName = "Полимеризатор", price = 1.0, currency = "res" },
{ internalName = "Genetics:misc:0", displayName = "Усиленный корпус", price = 1.0, currency = "res" },
{ internalName = "Genetics:misc:1", displayName = "ДНК-краситель", price = 1.0, currency = "res" },
{ internalName = "Genetics:misc:10", displayName = "Интегрированный ЦП", price = 1.0, currency = "res" },
{ internalName = "Genetics:misc:11", displayName = "Интегрированный корпус", price = 1.0, currency = "res" },
{ internalName = "Genetics:misc:2", displayName = "Флуоресцентный краситель", price = 1.0, currency = "res" },
{ internalName = "Genetics:misc:3", displayName = "Фермент", price = 1.0, currency = "res" },
{ internalName = "Genetics:misc:4", displayName = "Питательная среда", price = 1.0, currency = "res" },
{ internalName = "Genetics:misc:5", displayName = "Чистая последовательность", price = 1.0, currency = "res" },
{ internalName = "Genetics:misc:6", displayName = "Пустая сывороточная пробирка", price = 1.0, currency = "res" },
{ internalName = "Genetics:misc:9", displayName = "Интегрированная монтажная плата", price = 1.0, currency = "res" },
{ internalName = "Genetics:registry:0", displayName = "Регистр", price = 1.0, currency = "res" },
{ internalName = "GraviSuite:advChainsaw:1", displayName = "Продвинутая бензопила", price = 1.0, currency = "res" },
{ internalName = "GraviSuite:advChainsaw:27", displayName = "Продвинутая бензопила", price = 1.0, currency = "res" },
{ internalName = "GraviSuite:advDDrill:0", displayName = "Продвинутая алмазная дрель", price = 1.0, currency = "res" },
{ internalName = "GraviSuite:advLappack:0", displayName = "Продвинутый лазуротроновый ранец", price = 1.0, currency = "res" },
{ internalName = "GraviSuite:graviTool:0", displayName = "ГравиИнструмент", price = 1.0, currency = "res" },
{ internalName = "GraviSuite:itemSimpleItem:0", displayName = "Сверхпроводниковая оболочка", price = 1.0, currency = "res" },
{ internalName = "GraviSuite:itemSimpleItem:1", displayName = "Сверхпроводник", price = 1.0, currency = "res" },
{ internalName = "GraviSuite:itemSimpleItem:2", displayName = "Охлаждающее ядро", price = 1.0, currency = "res" },
{ internalName = "GraviSuite:itemSimpleItem:6", displayName = "Ускоритель двигателя", price = 1.0, currency = "res" },
{ internalName = "IC2:blockAlloy:0", displayName = "Усиленный камень", price = 1.0, currency = "res" },
{ internalName = "IC2:blockAlloyGlass:0", displayName = "Усиленное стекло", price = 1.0, currency = "res" },
{ internalName = "IC2:blockCrop:0", displayName = "Культура", price = 1.0, currency = "res" },
{ internalName = "IC2:blockElectric:0", displayName = "Батарейный ящик", price = 1.0, currency = "res" },
{ internalName = "IC2:blockElectric:1", displayName = "МФЭ", price = 1.0, currency = "res" },
{ internalName = "IC2:blockElectric:2", displayName = "МФСУ", price = 1.0, currency = "res" },
{ internalName = "IC2:blockElectric:3", displayName = "НН-Трансформатор", price = 1.0, currency = "res" },
{ internalName = "IC2:blockElectric:4", displayName = "СН-Трансформатор", price = 1.0, currency = "res" },
{ internalName = "IC2:blockElectric:5", displayName = "ВН-Трансформатор", price = 1.0, currency = "res" },
{ internalName = "IC2:blockElectric:6", displayName = "СВН-Трансформатор", price = 1.0, currency = "res" },
{ internalName = "IC2:blockFenceIron:0", displayName = "Железный забор", price = 1.0, currency = "res" },
{ internalName = "IC2:blockGenerator:0", displayName = "Генератор", price = 1.0, currency = "res" },
{ internalName = "IC2:blockGenerator:1", displayName = "Геотермальный генератор", price = 1.0, currency = "res" },
{ internalName = "IC2:blockGenerator:3", displayName = "Солнечная панель", price = 1.0, currency = "res" },
{ internalName = "IC2:blockGenerator:5", displayName = "Ядерный реактор", price = 1.0, currency = "res" },
{ internalName = "IC2:blockGenerator:9", displayName = "Кинетический генератор", price = 1.0, currency = "res" },
{ internalName = "IC2:blockHeatGenerator:3", displayName = "Электрический нагреватель", price = 1.0, currency = "res" },
{ internalName = "IC2:blockIronScaffold:0", displayName = "Железные строительные леса", price = 1.0, currency = "res" },
{ internalName = "IC2:blockKineticGenerator:0", displayName = "Кинетический ветрогенератор", price = 1.0, currency = "res" },
{ internalName = "IC2:blockMachine2:0", displayName = "Телепорт", price = 1.0, currency = "res" },
{ internalName = "IC2:blockMachine2:12", displayName = "Жидкостный теплообменник", price = 1.0, currency = "res" },
{ internalName = "IC2:blockMachine2:3", displayName = "Термальная центрифуга", price = 1.0, currency = "res" },
{ internalName = "IC2:blockMachine2:4", displayName = "Металлоформовщик", price = 1.0, currency = "res" },
{ internalName = "IC2:blockMachine2:5", displayName = "Рудопромывочная установка", price = 1.0, currency = "res" },
{ internalName = "IC2:blockMachine2:9", displayName = "Твердотельный наполнитель", price = 1.0, currency = "res" },
{ internalName = "IC2:blockMachine3:0", displayName = "Паровой генератор", price = 1.0, currency = "res" },
{ internalName = "IC2:blockMachine3:4", displayName = "Распределитель жидкости", price = 1.0, currency = "res" },
{ internalName = "IC2:blockMachine:0", displayName = "Базовый корпус машины", price = 1.0, currency = "res" },
{ internalName = "IC2:blockMachine:1", displayName = "Железная печь", price = 1.0, currency = "res" },
{ internalName = "IC2:blockMachine:11", displayName = "Переработчик", price = 1.0, currency = "res" },
{ internalName = "IC2:blockMachine:12", displayName = "Продвинутый корпус машины", price = 1.0, currency = "res" },
{ internalName = "IC2:blockMachine:13", displayName = "Индукционная печь", price = 1.0, currency = "res" },
{ internalName = "IC2:blockMachine:2", displayName = "Электрическая печь", price = 1.0, currency = "res" },
{ internalName = "IC2:blockMachine:3", displayName = "Дробилка", price = 1.0, currency = "res" },
{ internalName = "IC2:blockMachine:4", displayName = "Экстрактор", price = 1.0, currency = "res" },
{ internalName = "IC2:blockMachine:5", displayName = "Компрессор", price = 1.0, currency = "res" },
{ internalName = "IC2:blockMachine:6", displayName = "Жидкостный/твердотельный наполнитель", price = 1.0, currency = "res" },
{ internalName = "IC2:blockMetal:0", displayName = "Медный блок", price = 1.0, currency = "res" },
{ internalName = "IC2:blockMetal:1", displayName = "Оловянный блок", price = 1.0, currency = "res" },
{ internalName = "IC2:blockMetal:4", displayName = "Свинцовый блок", price = 1.0, currency = "res" },
{ internalName = "IC2:blockMetal:5", displayName = "Блок очищенного железа", price = 1.0, currency = "res" },
{ internalName = "IC2:blockPersonal:0", displayName = "Личный сейф", price = 1.0, currency = "res" },
{ internalName = "IC2:blockReactorAccessHatch:0", displayName = "Люк доступа к реактору", price = 1.0, currency = "res" },
{ internalName = "IC2:blockReactorChamber:0", displayName = "Камера реактора", price = 1.0, currency = "res" },
{ internalName = "IC2:blockReactorRedstonePort:0", displayName = "Редстоуновый порт реактора", price = 1.0, currency = "res" },
{ internalName = "IC2:blockRubSapling:0", displayName = "Саженец гевеи", price = 1.0, currency = "res" },
{ internalName = "IC2:blockRubWood:0", displayName = "Древесина гевеи", price = 1.0, currency = "res" },
{ internalName = "IC2:blockreactorvessel:0", displayName = "Корпус реактора", price = 1.0, currency = "res" },
{ internalName = "IC2:itemAdvBat:26", displayName = "Продвинутый аккумулятор", price = 1.0, currency = "res" },
{ internalName = "IC2:itemArmorAlloyChestplate:0", displayName = "Композитный жилет", price = 1.0, currency =
  
}
